---
- name: Test request
  uri:
    url: http://localhost:{{nginx_port}}
    method: GET
  register: _result
  until: _result.status == 200
  retries: 5
  delay: 1
  timeout: 5

# - debug: var=_result

- shell: systemctl status nginx
  register: status_nginx

- name: Test assert
  assert:
    that:
      - "'Active: active (running)' in status_nginx.stdout"

- name: Get stats of a file
  stat:
    path: /var/log/nginx/access.log
  register: status_log

- name: Fail if the file does not belong to 'root'
  fail:
    msg: "Whoops! file ownership has changed"
  when: status_log.stat.pw_name != 'root'
