filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  paths:
    - /var/log/web_analytics/web_analytics.log

# - type: docker
#   containers:
#     path: "/var/lib/docker/containers"
#     stream: "stdout"
#     ids:
#       - "*"

#output.file:
#  path: "/tmp/"
#  filename: filebeat-logs

output.logstash:
  hosts: ["127.0.0.1:5044"]


# docker run -d \
#   --name=filebeat \
#   --user=root \
#   --volume="$(pwd)/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro" \
#   --volume="/tmp/filebeat:/tmp" \
#   --volume="/var/log/web_analytics:/var/log/web_analytics" \
#   docker.elastic.co/beats/filebeat:7.14.1


# docker run -d \
#   --name=filebeat \
#   --user=root \
#   --volume="$(pwd)/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro" \
#   --volume="/var/lib/docker/containers:/var/lib/docker/containers:ro" \
#   --volume="/tmp/filebeat:/tmp" \
#   --volume="/var/run/docker.sock:/var/run/docker.sock:ro" \
#   docker.elastic.co/beats/filebeat:7.14.1
