---
- hosts: all
  name: Postgres deployment playbook
  gather_facts: no
  remote_user: ubuntu
  vars:
    pg_version: 15
    # ip_mask:
    ip_mask: "0.0.0.0/0"
  vars_files:
    - vars.yaml
  tasks:

    - import_tasks: install.yaml
      tags: install
    - include_tasks: update.yaml
      # tags: update

    # - debug:
    #     msg: "my_var = {{my_var}}"
    #
    # - name: Show message
    #   debugger: on_failed
    #   ping:
    #     data: "Var is {{wrong_var}}"

  handlers:
    - name: restart postgres
      become: yes
      service:
        name: postgresql
        state: restarted
      tags:
        - one
