---
- hosts: all
  name: deployment play 1
  remote_user: ubuntu
  # become: yes
  vars:
    package_1:
      - screen
      - net-tools
  tasks:
    - name: Install package_1
      become: yes
      apt:
        name: "{{ package_1 }}"
        state: present
        update_cache: yes

- hosts: all
  name: deployment play 2
  remote_user: ubuntu
  vars:
    package_2: git,screen,htop,wget,curl
  tasks:
    - name: Install package_2
      become: yes
      apt:
        name: "{{ package_2 }}"
        state: present
        update_cache: yes
